import React, { Suspense } from 'react'
import { Canvas } from '@react-three/fiber'
import { useGLTF, OrbitControls, PerspectiveCamera } from '@react-three/drei'
import "../style.css";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/91964c1ce1a34c3985b6257441efa500
*/
function Model({ url }) {
	const { nodes } = useGLTF(url)
	return (
		<group rotation={[-Math.PI / 2, 0, 0]} position={[0, -7, 0]} scale={8}>
			<group rotation={[Math.PI / 13.5, -Math.PI / 5.8, Math.PI / 5.6]}>
				<mesh receiveShadow castShadow geometry={nodes.planet002.geometry} material={nodes.planet002.material} />
				<mesh geometry={nodes.planet003.geometry} material={nodes.planet003.material} />
			</group>
		</group>
	)
}

export default function Space(props) {
	return (
		<>
			<Canvas
				{...props}
			>
				<fog attach="fog" args={['#272730', 30, 58]} />
				<ambientLight intensity={1} />
				<PerspectiveCamera makeDefault position={[-50, 0, 0]} fov={55} >
					<pointLight intensity={1} position={[-0, -25, -10]} />
					<spotLight castShadow intensity={1} angle={30} penumbra={40} position={[0, 80, -5]} shadow-mapSize={[1024, 1024]} shadow-bias={-0.003} />
				</PerspectiveCamera>
				<Suspense fallback={null}>
					<Model url="../space.glb" />
				</Suspense>
				<OrbitControls autoRotate enablePan={false} enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} />
			</Canvas>
			<div className="layer" />

		</>
	)
}